# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34102f6bfadd94d5cbd914eda8ab261a7510ad73d853a43a6c1234fe4ead177782d43a684ad7fbe5323a1142f52f6d2f1923837069b55a7e8ddc0d236021fbf9

test:
  secret_key_base: a18dbffcb8ade38de1b3b82f70b6e4a898a49694e99e9e37fc41e88b61be856f40bf3096d74823c7d9698c3dea003422dbb51aed3ceb3fb6715459b1f21faeb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
